# Configuración del sistema

chunk_size: 800
chunk_overlap: 100

top_k_chunks: 5

embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
qa_model: "distilbert-base-cased-distilled-squad"

persist_directory: "./chroma_db"
models_cache_dir: "./models_cache"

min_qa_score: 0.01

# NUEVO: Usar Qwen2.5-Math
use_qwen_math: true